#!/usr/bin/env python3
"""Generate a human-readable project dashboard from repository state."""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML required: python -m pip install pyyaml")

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "coordination" / "DASHBOARD.md"


def load_yaml(rel: str):
    path = ROOT / rel
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def read(rel: str) -> str:
    path = ROOT / rel
    return path.read_text(encoding="utf-8") if path.exists() else ""


def parse_table(text: str):
    rows = []
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cols = [c.strip() for c in line.strip("|").split("|")]
        if not cols or all(re.fullmatch(r":?-+:?", c or "") for c in cols):
            continue
        rows.append(cols)
    return rows


def open_questions():
    rows = parse_table(read("coordination/OPEN_QUESTIONS.md"))
    if rows and rows[0] and rows[0][0] == "ID":
        rows = rows[1:]
    return [
        r for r in rows
        if len(r) >= 4
        and r[0].startswith("OPEN-")
        and r[3] not in {"RESOLVED", "CANCELLED"}
    ]


def integration_queue():
    rows = parse_table(read("coordination/INTEGRATION_QUEUE.md"))
    if rows and rows[0] and rows[0][0] == "Order":
        rows = rows[1:]
    return [
        r for r in rows
        if len(r) >= 6 and r[1] != "-" and r[5] != "EMPTY"
    ]


def release_progress():
    text = read("coordination/RELEASE_CHECKLIST.md")
    boxes = re.findall(r"^- \[( |x|X)\] ", text, re.M)
    done = sum(1 for x in boxes if x.lower() == "x")
    return done, len(boxes)


def file_count(folder: str, prefix: str):
    path = ROOT / folder
    if not path.exists():
        return 0
    return sum(
        1 for p in path.glob(f"{prefix}*.md")
        if "TEMPLATE" not in p.name
    )


def task_summary():
    task_dir = ROOT / "coordination" / "tasks"
    statuses = Counter()
    types = Counter()
    active = []

    if not task_dir.exists():
        return statuses, types, active

    for path in sorted(task_dir.glob("TASK-*.md")):
        if path.name == "TASK_TEMPLATE.md":
            continue

        text = path.read_text(encoding="utf-8")
        sm = re.search(r"^## Status\s*\n+([A-Z_]+)\s*$", text, re.M)
        tm = re.search(r"^## Type\s*\n+([A-Z_]+)\s*$", text, re.M)
        om = re.search(r"^## Owner\s*\n+([^\n#]+)", text, re.M)

        status = sm.group(1) if sm else "UNKNOWN"
        typ = tm.group(1) if tm else "UNKNOWN"
        owner = om.group(1).strip() if om else "-"

        statuses[status] += 1
        types[typ] += 1

        if status in {
            "READY", "CLAIMED", "IN_PROGRESS", "BLOCKED",
            "REVIEW_READY", "IN_REVIEW"
        }:
            active.append((path.stem, typ, owner, status))

    return statuses, types, active


def render():
    state = load_yaml("coordination/PROJECT_STATE.yaml")
    meta = load_yaml("coordination/REPOSITORY_METADATA.yaml")

    project = state.get("project", {})
    repo_state = state.get("repository", {})
    agents = state.get("agents", {})
    metadata_repo = meta.get("repository", {})

    task_statuses, _, active_tasks = task_summary()
    questions = open_questions()
    queue = integration_queue()
    release_done, release_total = release_progress()
    bug_count = file_count("coordination/defects", "BUG-")
    debt_count = file_count("coordination/tech_debt", "TECHDEBT-")

    blockers = state.get("blockers", [])
    blockers = blockers if isinstance(blockers, list) else []

    lines = [
        "# Project Dashboard",
        "",
        "> Auto-generated from repository state. Do not edit this file manually.",
        "",
        "## Project",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Project | {project.get('name', '-')} |",
        f"| Status | **{project.get('status', '-')}** |",
        f"| Milestone | {project.get('milestone', '-')} |",
        f"| Version | **{project.get('version', '-')}** |",
        f"| Platform | {project.get('platform', '-')} |",
        f"| Host | {project.get('host', '-')} {project.get('host_version', '')} |",
        f"| Category | {repo_state.get('category', metadata_repo.get('category', '-'))} |",
        f"| Repository | {metadata_repo.get('expected_full_name', repo_state.get('repository_name', '-'))} |",
        f"| Template mode | {state.get('template_mode', '-')} |",
        "",
        "## Agents",
        "",
        "| Agent | Role | Status | Current Task |",
        "|---|---|---|---|",
    ]

    for key in sorted(agents):
        data = agents[key] or {}
        name = key.replace("_", " ").title()
        task = data.get("task") or "-"
        lines.append(
            f"| {name} | {data.get('role', '-')} | "
            f"**{data.get('status', '-')}** | {task} |"
        )

    lines += [
        "",
        "## Work Overview",
        "",
        "| Metric | Count |",
        "|---|---:|",
        f"| Active tasks | {len(active_tasks)} |",
        f"| Blockers | {len(blockers)} |",
        f"| Open questions | {len(questions)} |",
        f"| Integration queue | {len(queue)} |",
        f"| Defects | {bug_count} |",
        f"| Technical debt items | {debt_count} |",
        f"| Release checklist | {release_done}/{release_total} |",
        "",
    ]

    if task_statuses:
        lines += [
            "### Tasks by Status",
            "",
            "| Status | Count |",
            "|---|---:|",
        ]
        for status, count in sorted(task_statuses.items()):
            lines.append(f"| {status} | {count} |")
        lines.append("")

    if active_tasks:
        lines += [
            "### Active Tasks",
            "",
            "| Task | Type | Owner | Status |",
            "|---|---|---|---|",
        ]
        for task_id, typ, owner, status in active_tasks:
            lines.append(
                f"| [{task_id}](tasks/{task_id}.md) | {typ} | "
                f"{owner} | **{status}** |"
            )
        lines.append("")

    if blockers:
        lines += ["## Blockers", ""]
        for item in blockers:
            if isinstance(item, dict):
                ident = item.get("id", "BLOCKER")
                desc = item.get("description") or item.get("reason") or str(item)
                lines.append(f"- **{ident}:** {desc}")
            else:
                lines.append(f"- {item}")
        lines.append("")

    if questions:
        lines += [
            "## Open Questions",
            "",
            "| ID | Question | Owner | Status |",
            "|---|---|---|---|",
        ]
        for row in questions:
            lines.append(
                f"| {row[0]} | {row[1]} | {row[2]} | **{row[3]}** |"
            )
        lines.append("")

    if queue:
        lines += [
            "## Integration Queue",
            "",
            "| Order | Task | Branch / PR | Risk | Tests | Status |",
            "|---:|---|---|---|---|---|",
        ]
        for row in queue:
            lines.append("| " + " | ".join(row[:6]) + " |")
        lines.append("")

    lines += [
        "## Quick Links",
        "",
        "- [Blackboard](BLACKBOARD.md)",
        "- [Project State](PROJECT_STATE.yaml)",
        "- [Tasks](tasks/)",
        "- [Open Questions](OPEN_QUESTIONS.md)",
        "- [Integration Queue](INTEGRATION_QUEUE.md)",
        "- [Release Checklist](RELEASE_CHECKLIST.md)",
        "- [Repository Metadata](REPOSITORY_METADATA.yaml)",
        "- [Requirements](../docs/specifications/REQUIREMENTS.md)",
        "- [Architecture](../docs/developer/ARCHITECTURE.md)",
        "",
        "## Dashboard Rules",
        "",
        "- Source data stays in the canonical project files.",
        "- This dashboard contains no independent project truth.",
        "- Update canonical files, then run: python tools/generate_dashboard.py",
        "",
    ]

    return "\n".join(lines)


def main() -> int:
    OUT.write_text(render(), encoding="utf-8")
    print(f"Updated {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
